version: 1
disable_existing_loggers: False
formatters:
    custom:
        format: '[%(asctime)s][%(names)s][%(levelname)s] %(message)s'
        #datefmt: '%d-%b-%Y %r %Z'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: custom
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: DEBUG
        formatter: custom
        filename: !logfilename
        mode: 'w'
        encoding: utf8

loggers:
    newapp:
        level: !loglevel
        handlers: [file]
        propagate: no

root:
    level: !loglevel
    handlers: [file]
